<?php

require_once dirname(__FILE__) . '/../../twitteroauth/twitteroauth.php';

/**
 * Test class for TwitterOAuth.
 * Generated by PHPUnit on 2012-04-02 at 10:39:18.
 */
class TwitterOAuthTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var TwitterOAuth
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new TwitterOAuth('HOGE','FUGA');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * check accessTokenURL property
	 */
	public function testAccessTokenURL() {	
		$ret = $this->object->accessTokenURL();
		$exp = 'https://api.twitter.com/oauth/access_token';
		$this->assertEquals($exp, $ret, 'validate twitter api url.');
	}

	/**
	 * check authenticateURL property
	 */
	public function testAuthenticateURL() {
		$ret = $this->object->authenticateURL();
		$exp = 'https://api.twitter.com/oauth/authenticate';
		$this->assertEquals($exp, $ret, 'validate twitter api url.');
	}

	/**
	 * check authorizeURL property
	 */
	public function testAuthorizeURL() {
		$ret = $this->object->authorizeURL();
		$exp = 'https://api.twitter.com/oauth/authorize';
		$this->assertEquals($exp, $ret, 'validate twitter api url.');
	}

	/**
	 * @todo Implement testRequestTokenURL().
	 */
	public function testRequestTokenURL() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testLastStatusCode().
	 */
	public function testLastStatusCode() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testLastAPICall().
	 */
	public function testLastAPICall() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetRequestToken().
	 */
	public function testGetRequestToken() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAuthorizeURL().
	 */
	public function testGetAuthorizeURL() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAccessToken().
	 */
	public function testGetAccessToken() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetXAuthToken().
	 */
	public function testGetXAuthToken() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGet().
	 */
	public function testGet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPost().
	 */
	public function testPost() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDelete().
	 */
	public function testDelete() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testOAuthRequest().
	 */
	public function testOAuthRequest() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testHttp().
	 */
	public function testHttp() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetHeader().
	 */
	public function testGetHeader() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
